version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: gitea-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gitea
      MYSQL_USER: gitea
      MYSQL_PASSWORD: giteapass
    volumes:
      - ./mysql:/var/lib/mysql

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - mysql
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=giteapass
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./gitea:/data

  drone:
    image: drone/drone:2
    container_name: drone
    depends_on:
      - gitea
    ports:
      - "8000:80"
    volumes:
      - ./drone:/data
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GITEA_CLIENT_ID=e4bbfc04-f7e3-4a70-a6c1-815434a000f9
      - DRONE_GITEA_CLIENT_SECRET=gto_lyyy5wneysbkic6s2mlxw2lqmb2brabmavoxpzz5d772xyxndf6a
      - DRONE_RPC_SECRET=Andrew2005@
      - DRONE_SERVER_HOST=localhost:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_GITEA_URL=http://localhost:8000
      - DRONE_USER_CREATE=username:andryko101,admin:true

  drone-runner:
    image: drone/drone-runner-docker:1
    container_name: drone-runner
    depends_on:
      - drone
    ports:
      - "9000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=Andrew2005@
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=docker-runner
